{{- if .Values.podDisruptionBudget -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels: {{ include "sentry-kubernetes.labels" . | indent 4 }}
  name: {{ template "sentry-kubernetes.fullname" . }}

spec:
  selector:
    matchLabels:
      app: {{ template "sentry-kubernetes.name" . }}
{{ toYaml .Values.podDisruptionBudget | indent 2 }}
{{- end -}}
